/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BusinessLogic.DetalleVenta;
import BusinessLogic.utilJtextField;
import javax.swing.text.AbstractDocument;
import BusinessLogic.Venta;
import UI.Main;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Devolucion extends javax.swing.JFrame {

    /**
     * Creates new form Devoluciones
     */
    private Main parent;

    public Devolucion(Main parent) {
        this.parent = parent;
        initComponents();
        ((AbstractDocument) txtAnnio.getDocument()).setDocumentFilter(new utilJtextField(5));
        ((AbstractDocument) txtMes.getDocument()).setDocumentFilter(new utilJtextField(2));
        ((AbstractDocument) txtDia.getDocument()).setDocumentFilter(new utilJtextField(2));
    }

    public void llenarTablaVentas(ArrayList<Venta> ventas) {
        DefaultTableModel modelo = (DefaultTableModel) tableVentasDelDia.getModel();
        modelo.setRowCount(0);
        for (Venta v : ventas) {
            modelo.addRow(new Object[]{v.getFecha(),
                v.getID(),
                v.getTotalBruto(),
                v.getTotalVenta()});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPedirFecha = new javax.swing.JLabel();
        lblAnnio = new javax.swing.JLabel();
        txtAnnio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollListaVentasDia = new javax.swing.JScrollPane();
        tableVentasDelDia = new javax.swing.JTable();
        btnDevolver = new javax.swing.JButton();
        lblPresioneVenta = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        lblFormatoFecha = new javax.swing.JLabel();
        lblMM = new javax.swing.JLabel();
        lblDD = new javax.swing.JLabel();
        txtError = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPedirFecha.setText("Ingrese la fecha en la que se realizo la venta");

        lblAnnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnnio.setText("AAAA");

        ((AbstractDocument) txtAnnio.getDocument()).setDocumentFilter(new utilJtextField(10));
        txtAnnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnioActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        scrollListaVentasDia.setVisible(false);

        tableVentasDelDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableVentasDelDia.setEnabled(false);
        scrollListaVentasDia.setViewportView(tableVentasDelDia);

        btnDevolver.setVisible(false);
        btnDevolver.setBackground(new java.awt.Color(225, 10, 0));
        btnDevolver.setText("Hacer devolución");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        lblPresioneVenta.setVisible(false);
        lblPresioneVenta.setText("Presione la venta que quiera devolver y luego presione \"Hacer devolución\".");
        lblPresioneVenta.setName(""); // NOI18N

        ((AbstractDocument) txtAnnio.getDocument()).setDocumentFilter(new utilJtextField(10));
        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaActionPerformed(evt);
            }
        });

        ((AbstractDocument) txtAnnio.getDocument()).setDocumentFilter(new utilJtextField(10));
        txtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesActionPerformed(evt);
            }
        });

        lblFormatoFecha.setText("en formato AAAA-MM-DD");

        lblMM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMM.setText("MM");

        lblDD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDD.setText("DD");

        txtError.setColumns(20);
        txtError.setRows(5);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollListaVentasDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAnnio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(txtAnnio, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(lblMM, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscar)
                                    .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblFormatoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPedirFecha))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDevolver)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRegresar)
                                    .addComponent(lblPresioneVenta))
                                .addGap(25, 25, 25))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPedirFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFormatoFecha))
                    .addComponent(btnRegresar))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnnio)
                    .addComponent(lblMM)
                    .addComponent(lblDD)
                    .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblPresioneVenta)
                .addGap(9, 9, 9)
                .addComponent(scrollListaVentasDia, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String fechaString;
        ArrayList<Venta> ventasDelDia = null;
        String dia = txtDia.getText().trim();
        String mes = txtMes.getText().trim();
        String annio = txtAnnio.getText().trim();
        try {
            if(dia.isBlank() || mes.isBlank() || annio.isBlank()){
                throw new IllegalArgumentException("Todos los campos son obligatorios.");
            }
            int Dia = Integer.parseInt(dia);
            int Mes = Integer.parseInt(mes);
            int Annio = Integer.parseInt(annio);

            for (Venta v : parent.getCaja().getVentas()) {
                if (v.getFecha().getDayOfMonth() == Dia) {
                    if (v.getFecha().getMonthValue() == Mes) {
                        if (v.getFecha().getYear() == Annio) {

                            ventasDelDia.add(v);

                        }
                    }
                }
            }
            if (ventasDelDia == null) {
                throw new IllegalArgumentException("No se encontraron ventas en el día índicado");
            } else {
                this.llenarTablaVentas(ventasDelDia);
                this.tableVentasDelDia.setVisible(true);
                this.lblPresioneVenta.setVisible(true);
                this.btnDevolver.setVisible(true);
            }
        } catch (IllegalArgumentException ex) {
            txtError.setText(ex.getMessage());
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        int ventaSeleccionada = this.tableVentasDelDia.getSelectedRow();
        if (ventaSeleccionada == -1) {
        }
        else{
            ArrayList<DetalleVenta> detalles = null;
            int i = -1;
            long idVenta = (long)this.tableVentasDelDia.getValueAt(ventaSeleccionada, 1);
            for (Venta v : parent.getCaja().getVentas()) {
                i += 1;
                if(v.getID() == idVenta){
                    detalles = v.getDetalles();
                    break;
                }
            }
            for(DetalleVenta d : detalles){
                double cantidad = d.getCantidad()+parent.getCaja().getInventario().getCantidades().get(d.getProducto().getId());
                parent.getCaja().getInventario().getCantidades().replace(d.getProducto().getId(), cantidad);
            }
            
            parent.getCaja().getVentas().remove(i);
        }

    }//GEN-LAST:event_btnDevolverActionPerformed

    private void txtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaActionPerformed

    private void txtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblAnnio;
    private javax.swing.JLabel lblDD;
    private javax.swing.JLabel lblFormatoFecha;
    private javax.swing.JLabel lblMM;
    private javax.swing.JLabel lblPedirFecha;
    private javax.swing.JLabel lblPresioneVenta;
    private javax.swing.JScrollPane scrollListaVentasDia;
    private javax.swing.JTable tableVentasDelDia;
    private javax.swing.JTextField txtAnnio;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextArea txtError;
    private javax.swing.JTextField txtMes;
    // End of variables declaration//GEN-END:variables
}
