/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Entities.Producto;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class ReporteStock extends javax.swing.JFrame {
    private Main parent;
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form ReporteStock
     */
    public ReporteStock(Main parent) {
        this.parent = parent;
        initComponents();
        modeloTabla = (DefaultTableModel)tblReporteStock.getModel();
    }
    
   public void mostrarVentasEnTabla() {
        Map<Long, Double> cantidades = parent.getCaja().getInventario().filtrarStack();
        ArrayList<Producto> productos = parent.getCaja().getInventario().filtrarProductos(cantidades);

        modeloTabla.setRowCount(0);

        for (Long idProd : cantidades.keySet()) {
            String nombre = "";
            for (Producto producto : productos) {
                if (producto.getId() == idProd) {
                    nombre = producto.getNombre();
                    break;
                }
            }

            double cantidad = cantidades.get(idProd);
            String alerta = "";

            if (cantidad < 5) {
                alerta = "⚠️ Stock Critico";
            } else if (cantidad > 20) {
                alerta = "Sobrestock";
            } else {
                alerta = "Normal";
            }

            agregarFilaProducto(nombre, cantidad, alerta);
        }
    }

    public void agregarFilaProducto(String producto, Double cantidad, String alerta) {
        Object[] nuevaFila = {producto, cantidad, alerta};
        modeloTabla.addRow(nuevaFila);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReporteStock = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteStock = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        btnRegresarReporteStock = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReporteStock.setText("Reporte Stock de Productos:");

        tblReporteStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Alerta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReporteStock);

        btnRegresarReporteStock.setBackground(new java.awt.Color(247, 84, 73));
        btnRegresarReporteStock.setText("Regresar");
        btnRegresarReporteStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarReporteStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblReporteStock))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresarReporteStock)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnRegresarReporteStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReporteStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarReporteStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarReporteStockActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarReporteStockActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRegresarReporteStock;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReporteStock;
    private javax.swing.JTable tblReporteStock;
    // End of variables declaration//GEN-END:variables
}
