/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author migue
 */
public class SistemaReportes extends javax.swing.JFrame {
    private Main parent;
    /**
     * Creates new form SistemaReportes
     */
    public SistemaReportes(Main parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReportesDeseaHacer = new javax.swing.JLabel();
        btnReporteVentas = new javax.swing.JButton();
        btnReporteStock = new javax.swing.JButton();
        btnRegresarReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReportesDeseaHacer.setText("¿Qué reporte desea consultar?");

        btnReporteVentas.setText("Reporte de Ventas");
        btnReporteVentas.setToolTipText("");
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });

        btnReporteStock.setText("Reporte de Stack");
        btnReporteStock.setToolTipText("");
        btnReporteStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteStockActionPerformed(evt);
            }
        });

        btnRegresarReportes.setText("Regresar");
        btnRegresarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportesDeseaHacer)
                    .addComponent(btnReporteVentas)
                    .addComponent(btnReporteStock))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresarReportes)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(lblReportesDeseaHacer)
                .addGap(39, 39, 39)
                .addComponent(btnReporteVentas)
                .addGap(18, 18, 18)
                .addComponent(btnReporteStock)
                .addGap(57, 57, 57)
                .addComponent(btnRegresarReportes)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        var reporteVentas = new ReporteVentas(parent);
        reporteVentas.setVisible(true);
    }//GEN-LAST:event_btnReporteVentasActionPerformed

    private void btnReporteStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteStockActionPerformed
       var ReporteStock = new ReporteStock(parent);
       ReporteStock.setVisible(true);
       ReporteStock.mostrarVentasEnTabla();
    }//GEN-LAST:event_btnReporteStockActionPerformed

    private void btnRegresarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarReportesActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarReportesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarReportes;
    private javax.swing.JButton btnReporteStock;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JLabel lblReportesDeseaHacer;
    // End of variables declaration//GEN-END:variables
}
