/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Gestión.Venta;
import java.util.stream.Collectors;

/**
 *
 * @author migue
 */
public class VentasPeriodo extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    private ArrayList<Venta> ventasAMostrar;
            
    /**
     * Creates new form VentasPeriodo
     */
    public VentasPeriodo(ArrayList<Venta> ventasAMotrar) {
        initComponents();
        modeloTabla = (DefaultTableModel) tblVentasFiltradas.getModel();
        this.ventasAMostrar = ventasAMotrar;
        mostrarVentasEnTabla(ventasAMotrar);
    }
    
    public void agregarFilaVenta(Object fecha, Object productos, Double totalVentas){
        Object[] nuevaFila = {fecha, productos, totalVentas};
        modeloTabla.addRow(nuevaFila);
    }
    
    public void mostrarVentasEnTabla(ArrayList<Venta> ventasAMostrar) {
        modeloTabla.setRowCount(0);
        
        for (Venta venta : ventasAMostrar) {
            LocalDateTime fechaVenta = venta.getFecha();
            double totalVenta = venta.getTotalVenta();

            String productosVendidos = venta.getDetalles().stream()
                    .map(detalle -> detalle.getProducto().getNombre() 
                            + " x" + detalle.getCantidad())
                    .collect(Collectors.joining(", "));

            agregarFilaVenta(fechaVenta, productosVendidos, totalVenta);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVentasFiltradas = new javax.swing.JScrollPane();
        tblVentasFiltradas = new javax.swing.JTable();
        scrollVentasFiltradas = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblVentasFiltradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Productos", "Total Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPanelVentasFiltradas.setViewportView(tblVentasFiltradas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVentasFiltradas, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(scrollVentasFiltradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVentasFiltradas, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollVentasFiltradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanelVentasFiltradas;
    private javax.swing.JScrollBar scrollVentasFiltradas;
    private javax.swing.JTable tblVentasFiltradas;
    // End of variables declaration//GEN-END:variables
}
