/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.DetalleVenta;
import BusinessLogic.Venta;
import BusinessLogic.VentaService;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Devolucion extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private VentaService ventaService;
    private Main main;

    /**
     * Creates new form Devolucion
     */
    public Devolucion() {
        initComponents();
        initJTable();
    }

    public Devolucion(VentaService ventaService, Main main) {
        this.modeloTabla = new DefaultTableModel();
        this.ventaService = ventaService;
        this.main = main;
        initComponents();
        initJTable();

    }

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public void setModeloTabla(DefaultTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }

    public VentaService getVentaService() {
        return ventaService;
    }

    public void setVentaService(VentaService ventaService) {
        this.ventaService = ventaService;
    }

    public Main getMain() {
        return main;
    }

    public void setMain(Main main) {
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFechaInicioConsultar = new javax.swing.JLabel();
        txtDiaFin = new javax.swing.JTextField();
        txtMesInicio = new javax.swing.JTextField();
        txtMesFin = new javax.swing.JTextField();
        lblMesFin = new javax.swing.JLabel();
        txtAnioFin = new javax.swing.JTextField();
        lblFechaFinConsultar = new javax.swing.JLabel();
        lblDiaInicio = new javax.swing.JLabel();
        txtAnioInicio = new javax.swing.JTextField();
        lblDiaFin = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        lblAnioInicio = new javax.swing.JLabel();
        lblIdVentaRequerido = new javax.swing.JLabel();
        lblSelecPeriodoTiempo = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();
        txtDiaInicio = new javax.swing.JTextField();
        lblMesInicio = new javax.swing.JLabel();
        lblAnioFin = new javax.swing.JLabel();
        btnDevolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        scrollPanelVentasFiltradas = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        lblFechaInicioConsultar.setText("Fecha Inicio:");

        txtMesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesInicioActionPerformed(evt);
            }
        });

        txtMesFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesFinActionPerformed(evt);
            }
        });

        lblMesFin.setText("MM");

        txtAnioFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioFinActionPerformed(evt);
            }
        });

        lblFechaFinConsultar.setText("Fecha fin:");

        lblDiaInicio.setText("DD");

        txtAnioInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioInicioActionPerformed(evt);
            }
        });

        lblDiaFin.setText("DD");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblAnioInicio.setText("AAAA");

        lblIdVentaRequerido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdVentaRequerido.setText("Ingrese el Id de la venta a devolver");
        lblIdVentaRequerido.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblSelecPeriodoTiempo.setText("Seleccione el periodo de tiempo a consultar:");

        txtIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVentaActionPerformed(evt);
            }
        });

        lblMesInicio.setText("MM");

        lblAnioFin.setText("AAAA");

        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane2.setViewportView(txtError);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelecPeriodoTiempo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFechaInicioConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDiaInicio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblIdVentaRequerido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFechaFinConsultar)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblDiaFin)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtMesFin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAnioFin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblMesFin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblAnioFin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDevolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblSelecPeriodoTiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicioConsultar)
                    .addComponent(txtDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaInicio)
                    .addComponent(lblMesInicio)
                    .addComponent(lblAnioInicio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaFinConsultar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMesFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnioFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaFin)
                            .addComponent(lblMesFin)
                            .addComponent(lblAnioFin))))
                .addGap(18, 18, 18)
                .addComponent(btnConsultar)
                .addGap(18, 18, 18)
                .addComponent(lblIdVentaRequerido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Productos", "ID", "Total Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPanelVentasFiltradas.setViewportView(tblVentas);
        if (tblVentas.getColumnModel().getColumnCount() > 0) {
            tblVentas.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelVentasFiltradas, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPanelVentasFiltradas, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMesFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesFinActionPerformed

    private void txtAnioFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioFinActionPerformed

    private void txtMesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesInicioActionPerformed

    private void txtAnioInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioInicioActionPerformed

    private void txtIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVentaActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        try {

        } catch (Exception ex) {
            txtError.setText(ex.getMessage());

        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String diaInicioStr = txtDiaInicio.getText().trim();
        String mesInicioStr = txtMesInicio.getText().trim();
        String anioInicioStr = txtAnioInicio.getText().trim();
        String diaFinStr = txtDiaFin.getText().trim();
        String mesFinStr = txtMesFin.getText().trim();
        String anioFinStr = txtAnioFin.getText().trim();

        LocalDate fechaInicio = null;
        LocalDate fechaFin = null;

        try {

            if (diaInicioStr.isBlank() || mesInicioStr.isBlank() || anioInicioStr.isBlank()
                    || diaFinStr.isBlank() || mesFinStr.isBlank() || anioFinStr.isBlank()) {
                throw new IllegalArgumentException("Todos los campos son obligatorios.");
            }

            int diaInicio = Integer.parseInt(diaInicioStr);
            int mesInicio = Integer.parseInt(mesInicioStr);
            int anioInicio = Integer.parseInt(anioInicioStr);
            int diaFin = Integer.parseInt(diaFinStr);
            int mesFin = Integer.parseInt(mesFinStr);
            int anioFin = Integer.parseInt(anioFinStr);

            fechaInicio = LocalDate.of(anioInicio, mesInicio, diaInicio);
            fechaFin = LocalDate.of(anioFin, mesFin, diaFin);

            ArrayList<Venta> ventasAMostrar = new ArrayList<>();

            try {
                ventasAMostrar = this.getVentaService().obtenerVentasSegunPeriodo(fechaInicio, fechaFin);
            } catch (Exception ex) {
            }
            for (Venta venta : ventasAMostrar) {
                StringBuilder productos = new StringBuilder();
                String producto;
                for (DetalleVenta detalle : venta.getDetalles()) {
                    producto = detalle.getProducto().getNombre();
                    productos.append(producto).append(", ");
                }
                this.agregarVentaFila(venta.getFecha(), venta.getID(), productos, venta.getTotalVenta());
            }

        } catch (NumberFormatException e) {
            txtError.setText("Error: Ingrese números válidos.");
        } catch (DateTimeException e) {
            if (e.getMessage().contains("inicio")) {
                txtError.setText("Error en Fecha Inicio: " + e.getMessage());
            } else if (e.getMessage().contains("fin")) {
                txtError.setText("Error en Fecha Fin: " + e.getMessage());
            } else {
                txtError.setText("Error de fecha.");
            }
        } catch (IllegalArgumentException e) {
            System.err.println(e.getMessage());
            txtError.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed
    public void agregarVentaFila(LocalDateTime fecha, long ID, StringBuilder productos, double totalVenta) {

        Object[] rowData = {
            fecha,
            ID,
            productos,
            totalVenta
        };

        modeloTabla.addRow(rowData);
    }

    private void initJTable() {
        modeloTabla = new DefaultTableModel();
        tblVentas.setModel(modeloTabla);
        String[] newColumnNames = {"Fecha",
            "ID",
            "Productos",
            "totalVenta"};
        modeloTabla.setColumnIdentifiers(newColumnNames);
        modeloTabla = new DefaultTableModel(newColumnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblVentas.setModel(modeloTabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnioFin;
    private javax.swing.JLabel lblAnioInicio;
    private javax.swing.JLabel lblDiaFin;
    private javax.swing.JLabel lblDiaInicio;
    private javax.swing.JLabel lblFechaFinConsultar;
    private javax.swing.JLabel lblFechaInicioConsultar;
    private javax.swing.JLabel lblIdVentaRequerido;
    private javax.swing.JLabel lblMesFin;
    private javax.swing.JLabel lblMesInicio;
    private javax.swing.JLabel lblSelecPeriodoTiempo;
    private javax.swing.JScrollPane scrollPanelVentasFiltradas;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtAnioFin;
    private javax.swing.JTextField txtAnioInicio;
    private javax.swing.JTextField txtDiaFin;
    private javax.swing.JTextField txtDiaInicio;
    private javax.swing.JTextArea txtError;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtMesFin;
    private javax.swing.JTextField txtMesInicio;
    // End of variables declaration//GEN-END:variables
}
