/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.Caja;
import BusinessLogic.Empleado;
import BusinessLogic.helperUI;
import java.util.ArrayList;

/**
 *
 * @author DELL
 */
public class EntrarSistema extends javax.swing.JInternalFrame{

    /**
     * Creates new form EntrarSistema
     */
    private Caja caja;
    private Main main;

    public EntrarSistema() {
        initComponents();
    }

    public EntrarSistema(Caja caja, Main main) {
        initComponents();
        this.caja = caja;
        this.main = main;
    }

    public Caja getCaja() {
        return caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }

    public Main getMain() {
        return main;
    }

    public void setMain(Main main) {
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreEmpleado = new javax.swing.JTextField();
        txtCedulaEmpleado = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtErrorRegistro = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);

        txtNombreEmpleado.setText(" ");
        txtNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpleadoActionPerformed(evt);
            }
        });

        txtCedulaEmpleado.setText(" ");
        txtCedulaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaEmpleadoActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre:");

        lblCedula.setText("Cedula:");

        btnIngresar.setBackground(new java.awt.Color(50, 155, 225));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtErrorRegistro.setColumns(20);
        txtErrorRegistro.setRows(5);
        jScrollPane1.setViewportView(txtErrorRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnIngresar)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoActionPerformed

    }//GEN-LAST:event_txtNombreEmpleadoActionPerformed

    private void txtCedulaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaEmpleadoActionPerformed

    }//GEN-LAST:event_txtCedulaEmpleadoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String nombre = txtNombreEmpleado.getText().trim();
        String cedula = txtCedulaEmpleado.getText().trim();
        try {

            if (nombre.isBlank() || cedula.isBlank() || nombre.isBlank() || cedula.isBlank()) {
                throw new IllegalArgumentException("Todos los campos son obligatorios.");
            }

            if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
                throw new IllegalArgumentException("El nombre solo puede contener letras y espacios.");
            }

            if (!cedula.matches("\\d+")) {
                throw new IllegalArgumentException("La cedula solo debe contener números.");
            }
            Empleado cajero = this.getCaja().verificarEmpleado(nombre, cedula);

            if (cajero != null) {

                this.getCaja().setCajero(cajero);
                this.getMain().getBtnHacerVenta().setEnabled(true);
                this.getMain().getBtnInventario().setEnabled(true);
                this.getMain().getBtnReportes().setEnabled(true);
                this.getMain().getBtnDevolución().setEnabled(true);
                this.getMain().getCerrarSesionItem().setEnabled(true);
                this.limpiarCampos();
                this.dispose();
            } else {
                txtErrorRegistro.setText("El usuario no existe.");
            }
        } catch (IllegalArgumentException ex) {
            txtErrorRegistro.setText(ex.getMessage());
        } catch (Exception ex) {
            txtErrorRegistro.setText("Error inesperado " + ex.getMessage());
        }
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnIngresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCedulaEmpleado;
    private javax.swing.JTextArea txtErrorRegistro;
    private javax.swing.JTextField txtNombreEmpleado;
    // End of variables declaration//GEN-END:variables

    public void limpiarCampos() {
        ArrayList<javax.swing.JTextField> campos = new ArrayList<>();
        campos.add(txtCedulaEmpleado);
        campos.add(txtNombreEmpleado);
        helperUI.limpiarCampos(campos);

    }
}
