/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.Caja;
import BusinessLogic.Producto;
import BusinessLogic.helperUI;
import java.util.ArrayList;
import java.util.NoSuchElementException;

/**
 *
 * @author DELL
 */
public class InventarioSistema extends javax.swing.JInternalFrame{

    private Producto productoBuscado;
    private Caja caja;
    private CreacionProducto crearProducto;

    /**
     * Creates new form InventarioSistema
     */
    public InventarioSistema() {
        initComponents();
    }

    public InventarioSistema(Caja caja) {
        this.productoBuscado = null;
        this.caja = caja;
        initComponents();
    }

    //setters y getters
    public Producto getProductoBuscado() {
        return productoBuscado;
    }

    public void setProductoBuscado(Producto productoBuscado) {
        this.productoBuscado = productoBuscado;
    }

    public Caja getCaja() {
        return caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }

    public CreacionProducto getCrearProducto() {
        return crearProducto;
    }

    public void setCrearProducto(CreacionProducto crearProducto) {
        this.crearProducto = crearProducto;
    }

    //metodos para la clase.
    private void setearCampos(Producto producto) {
        txtNombre.setEditable(false);
        txtTipo.setEditable(false);
        txtID.setEditable(false);
        txtCantidad.setEditable(false);
        txtPrecio.setEditable(false);
        txtPrecioMayorista.setEditable(false);
        txtNombre.setText(producto.getNombre());
        txtTipo.setText(String.valueOf(producto.getTipoProducto()));
        txtID.setText(String.valueOf(producto.getId()));
        Double cantidad = this.getCaja().getInventario().getCantidades().get(producto.getId());
        txtCantidad.setText(Double.toString(cantidad));
        txtPrecio.setText(String.valueOf(producto.getPrecio()));
        txtPrecioMayorista.setText(String.valueOf(producto.getPrecioMayorista()));
        txtFichaProducto.setText(producto.imprimirFicha());
    }

    public void limpiarCampos() {
        ArrayList<javax.swing.JTextField> campos = new ArrayList<>();
        campos.add(txtNombre);
        campos.add(txtCantidad);
        campos.add(txtPrecioMayorista);
        campos.add(txtPrecio);
        campos.add(txtID);
        campos.add(txtTipo);
        helperUI.limpiarCampos(campos);
        txtFichaProducto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        lblNombre = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPrecioMayorista = new javax.swing.JLabel();
        lblPrecioMenor = new javax.swing.JLabel();
        txtCantidadAjustar = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAjustarCantidad = new javax.swing.JToggleButton();
        txtTipo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFichaProducto = new javax.swing.JTextArea();
        txtCantidad = new javax.swing.JTextField();
        btnCrearProducto = new javax.swing.JToggleButton();
        txtPrecioMayorista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtError.setColumns(20);
        txtError.setRows(5);
        jScrollPane1.setViewportView(txtError);

        lblNombre.setText("Nombre");

        lblTipo.setText("Tipo");

        lblCantidad.setText("Cantidad");

        lblID.setText("       ID");

        lblPrecioMayorista.setText("Precio Mayor");

        lblPrecioMenor.setText("Precio Menor");

        txtCantidadAjustar.setMaximumSize(new java.awt.Dimension(124, 22));
        txtCantidadAjustar.setMinimumSize(new java.awt.Dimension(124, 22));
        txtCantidadAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadAjustarActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnAjustarCantidad.setText("Ajustar cantidad");
        btnAjustarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustarCantidadActionPerformed(evt);
            }
        });

        txtFichaProducto.setColumns(20);
        txtFichaProducto.setRows(5);
        jScrollPane2.setViewportView(txtFichaProducto);

        btnCrearProducto.setText("Crear Producto");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ficha");

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblNombre)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAjustarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidadAjustar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCantidad)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTipo)))
                            .addComponent(lblPrecioMayorista)
                            .addComponent(lblPrecioMenor)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPrecioMayorista, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnCrearProducto))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAjustarCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidadAjustar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioMayorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioMayorista))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioMenor))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(159, 159, 159))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiarCampos();
        String busqueda = txtBuscar.getText();
        try {
            if (busqueda.isEmpty() || busqueda.isBlank()) {
                throw new IllegalArgumentException("Todos los campos son obligatorios.");
            }
            boolean encontrado = false;

            if (busqueda.matches("\\d+")) {

                if (this.getCaja().getInventario().buscarProductos("ID", busqueda) != null) {
                    this.setProductoBuscado(this.getCaja().getInventario().buscarProductos("ID", busqueda));
                    setearCampos(this.getProductoBuscado());
                    encontrado = true;
                } else {
                    encontrado = false;
                }
            } else {
                if (this.getCaja().getInventario().buscarProductos("nombre", busqueda) != null) {
                    this.setProductoBuscado(this.getCaja().getInventario().buscarProductos("nombre", busqueda));
                    setearCampos(this.getProductoBuscado());
                    encontrado = true;
                } else {
                    encontrado = false;
                }
            }

            if (!encontrado) {
                throw new NoSuchElementException("Producto no encontrado.");
            }

        } catch (IllegalArgumentException ex) {
            txtError.setText(ex.getMessage());
        } catch (Exception ex) {
            txtError.setText("Error inesperado: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCantidadAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadAjustarActionPerformed

    }//GEN-LAST:event_txtCantidadAjustarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAjustarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustarCantidadActionPerformed

        try {
            String cantidad = txtCantidadAjustar.getText().trim();
            String busqueda = txtBuscar.getText();

            if (busqueda.isEmpty() || busqueda.isBlank() || cantidad.isBlank() || cantidad.isEmpty()) {
                throw new IllegalArgumentException("Todos los campos son obligatorios.");

            } else {
                if (!cantidad.matches("\\d+")) {
                    throw new IllegalArgumentException("La cantidad solo debe contener números positivos.");
                }
                if (this.productoBuscado == null) {
                    throw new IllegalArgumentException("Producto no encontrado.");
                }
            }
            Double cantidadAjustar = Double.valueOf(cantidad);
            this.getCaja().getInventario().getCantidades().replace(this.getProductoBuscado().getId(), cantidadAjustar);
            this.btnBuscarActionPerformed(evt);
            this.txtCantidadAjustar.setText("");
        } catch (IllegalArgumentException ex) {
            txtError.setText(ex.getMessage());
        } catch (Exception ex) {
            txtError.setText("Error inesperado: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAjustarCantidadActionPerformed

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        if (this.getCrearProducto() == null) {
            this.setCrearProducto(new CreacionProducto(this.getCaja(), this));
            this.getParent().add(this.getCrearProducto());
        }
        if (!this.getCrearProducto().isVisible()) {
            if (this.getCrearProducto().isClosed()) {
                this.getParent().add(this.getCrearProducto());
            }
            this.getCrearProducto().setVisible(true);
        }
    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAjustarCantidad;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JToggleButton btnCrearProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioMayorista;
    private javax.swing.JLabel lblPrecioMenor;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadAjustar;
    private javax.swing.JTextArea txtError;
    private javax.swing.JTextArea txtFichaProducto;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioMayorista;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
