/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.Producto;
import BusinessLogic.ProductoService;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class InventarioFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form InventarioFrame
     */
    private ProductoService productoService;
    private DefaultTableModel modeloTabla;

    public InventarioFrame(ProductoService productoService) throws Exception {
        initComponents();
        initJTable();
        initAdditional(productoService);
    }

    public ProductoService getProductoService() {
        return productoService;
    }

    public void setProductoService(ProductoService productoService) {
        this.productoService = productoService;
    }

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public void setModeloTabla(DefaultTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }

    public JTable getTblInventario() {
        return tblInventario;
    }

    public void setTblInventario(JTable tblInventario) {
        this.tblInventario = tblInventario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoría", "Nombre", "Cantidad", "Precio", "Precio (Mayorista)", "Fecha de Vencimiento", "Etiquetas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarProductos() throws Exception {
        var productos = this.getProductoService().getProductos();
        for (Map.Entry<Producto, Integer> entrada : productos.entrySet()) {
            var producto = entrada.getKey();
            var cantidad = entrada.getValue();
            var id = producto.getId();
            var categoria = producto.getTipoProducto().toString();
            var nombre = producto.getNombre();
            var precio = producto.getPrecio();
            var precioMayorista = producto.getPrecioMayorista();
            var fechaVencimiento = producto.getFechaDeVencimiento().toString();
            StringBuilder etiquetas = new StringBuilder();
            if (producto.getEtiquetas() != null){
                for (String etiqueta: producto.getEtiquetas()){
                etiquetas.append(etiqueta).append(", ");
                }
            } else{
                etiquetas.append("El producto no tiene etiquetas.");
            }
            
            
            agregarProducto(id, categoria, nombre, cantidad, precio, precioMayorista,
                    fechaVencimiento, etiquetas.toString());
        }
    }

    public void agregarProducto(Long id, String categoria, String nombre, int cantidad, double precio,
            double precioMayorista, String fechaVencimiento, String etiquetas) {
        Object[] rowData = {
            id,
            categoria,
            nombre,
            cantidad,
            String.format("%.2f", precio),
            String.format("%.2f", precioMayorista),
            fechaVencimiento,
            etiquetas,};

        modeloTabla.addRow(rowData);
    }

    private void initJTable() {
        modeloTabla = new DefaultTableModel();
        tblInventario.setModel(modeloTabla);
        String[] newColumnNames = {"ID", "Categoría", "Nombre", "Cantidad", "Precio",
            "Precio Mayorista", "Fecha de Vencimiento", "Etiquetas"};
        modeloTabla.setColumnIdentifiers(newColumnNames);
        modeloTabla = new DefaultTableModel(newColumnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblInventario.setModel(modeloTabla);
    }

    private void initAdditional(ProductoService productoService) throws Exception {
        this.productoService = productoService;
        this.mostrarProductos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventario;
    // End of variables declaration//GEN-END:variables
}
