/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package UI2;

import BusinessLogic.Caja;
import BusinessLogic.Empleado;
import BusinessLogic.Inventario;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JToggleButton;

/**
 *
 * @author Sebastian
 */
public class Main extends javax.swing.JFrame {

    private RegistroEmpleado registroEmpleado;
    private EntrarSistema entrarSistema;
    private Caja caja;
    private Inventario inventario;
    private InventarioSistema inventarioSistema;
    private MenuVenta venta;

    //private MenuDevolucion devolucion;
    private SistemaReportes sistemaReportes;

    public Main() {
        initComponents();
        initObjects();
        initFrames();
    }

    public Caja getCaja() {
        return caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }

    public Inventario getInventario() {
        return inventario;
    }

    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }

    // Getters y Setters
    public EntrarSistema getEntrarSistema() {
        return entrarSistema;
    }

    public void setEntrarSistema(EntrarSistema entrarSistema) {
        this.entrarSistema = entrarSistema;
    }

    public RegistroEmpleado getRegistrarEmpleado() {
        return registroEmpleado;
    }

    public void setRegistrarEmpleado(RegistroEmpleado registroEmpleado) {
        this.registroEmpleado = registroEmpleado;
    }

    public InventarioSistema getInventarioSistema() {
        return inventarioSistema;
    }

    public void setInventarioSistema(InventarioSistema inventarioSistema) {
        this.inventarioSistema = inventarioSistema;
    }

    public MenuVenta getVenta() {
        return venta;
    }

    public void setVenta(MenuVenta venta) {
        this.venta = venta;
    }

    /*
    public MenuDevolucion getDevolucion() {
        return devolucion;
    }

    public void setDevolucion(MenuDevolucion devolucion) {
        this.devolucion = devolucion;
    }
*/
    public SistemaReportes getSistemaReportes() {
        return sistemaReportes;
    }

    public void setSistemaReportes(SistemaReportes sistemaReportes) {
        this.sistemaReportes = sistemaReportes;
    }

    public JToggleButton getBtnDevolución() {
        return btnDevolución;
    }

    public void setBtnDevolución(JToggleButton btnDevolución) {
        this.btnDevolución = btnDevolución;
    }

    public JToggleButton getBtnHacerVenta() {
        return btnHacerVenta;
    }

    public void setBtnHacerVenta(JToggleButton btnHacerVenta) {
        this.btnHacerVenta = btnHacerVenta;
    }

    public JToggleButton getBtnInventario() {
        return btnInventario;
    }

    public void setBtnInventario(JToggleButton btnInventario) {
        this.btnInventario = btnInventario;
    }

    public JButton getBtnReportes() {
        return btnReportes;
    }

    public void setBtnReportes(JButton btnReportes) {
        this.btnReportes = btnReportes;
    }

    public JMenuItem getCerrarSesionItem() {
        return cerrarSesionItem;
    }

    public void setCerrarSesionItem(JMenuItem cerrarSesionItem) {
        this.cerrarSesionItem = cerrarSesionItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnter = new javax.swing.JButton();
        btnRegisterEmployee = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        txtButtonTienda1 = new javax.swing.JLabel();
        btnHacerVenta = new javax.swing.JToggleButton();
        btnDevolución = new javax.swing.JToggleButton();
        btnInventario = new javax.swing.JToggleButton();
        btnReportes = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuIncio = new javax.swing.JMenu();
        iniciarSesionItem = new javax.swing.JMenuItem();
        registrarEmpleadoItem = new javax.swing.JMenuItem();
        cerrarSesionItem = new javax.swing.JMenuItem();

        btnEnter.setText("Entrar al Sistema");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnRegisterEmployee.setText("Registrar Empleado");
        btnRegisterEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterEmployeeActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtButtonTienda1.setText("¿Qué desea hacer?");
        txtButtonTienda1.setMaximumSize(new java.awt.Dimension(100, 16));
        desktopPane.add(txtButtonTienda1);
        txtButtonTienda1.setBounds(280, 140, 97, 16);

        btnHacerVenta.setText("Hacer Venta");
        btnHacerVenta.setEnabled(false);
        btnHacerVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerVentaActionPerformed(evt);
            }
        });
        desktopPane.add(btnHacerVenta);
        btnHacerVenta.setBounds(110, 230, 94, 23);

        btnDevolución.setText("Devolución");
        btnDevolución.setEnabled(false);
        btnDevolución.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevoluciónActionPerformed(evt);
            }
        });
        desktopPane.add(btnDevolución);
        btnDevolución.setBounds(420, 230, 120, 23);

        btnInventario.setText("Inventario");
        btnInventario.setEnabled(false);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        desktopPane.add(btnInventario);
        btnInventario.setBounds(110, 300, 83, 23);

        btnReportes.setText("Reportes");
        btnReportes.setEnabled(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        desktopPane.add(btnReportes);
        btnReportes.setBounds(420, 300, 120, 23);

        menuIncio.setMnemonic('f');
        menuIncio.setText("Inicio");

        iniciarSesionItem.setMnemonic('o');
        iniciarSesionItem.setText("Iniciar Sesion");
        iniciarSesionItem.setToolTipText("");
        iniciarSesionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionItemActionPerformed(evt);
            }
        });
        menuIncio.add(iniciarSesionItem);

        registrarEmpleadoItem.setMnemonic('s');
        registrarEmpleadoItem.setText("Registrar Empleado");
        registrarEmpleadoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpleadoItemActionPerformed(evt);
            }
        });
        menuIncio.add(registrarEmpleadoItem);

        cerrarSesionItem.setMnemonic('x');
        cerrarSesionItem.setText("Cerrar Sesion");
        cerrarSesionItem.setEnabled(false);
        cerrarSesionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionItemActionPerformed(evt);
            }
        });
        menuIncio.add(cerrarSesionItem);

        menuBar.add(menuIncio);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionItemActionPerformed
        this.getBtnHacerVenta().setEnabled(false);
        this.getBtnInventario().setEnabled(false);
        this.getBtnReportes().setEnabled(false);
        this.getBtnDevolución().setEnabled(false);
        this.getCerrarSesionItem().setEnabled(false);
        this.getCaja().setCajero(null);
    }//GEN-LAST:event_cerrarSesionItemActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed

    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnRegisterEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterEmployeeActionPerformed

    }//GEN-LAST:event_btnRegisterEmployeeActionPerformed

    private void iniciarSesionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionItemActionPerformed
        if (entrarSistema == null) {
            entrarSistema = new EntrarSistema();
        }

        if (!entrarSistema.isVisible()) {
            if (entrarSistema.isClosed()) {
                desktopPane.add(entrarSistema);
            }
            entrarSistema.show();
        }
    }//GEN-LAST:event_iniciarSesionItemActionPerformed

    private void registrarEmpleadoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpleadoItemActionPerformed
        if (registroEmpleado == null) {
            registroEmpleado = new RegistroEmpleado();
        }

        if (!registroEmpleado.isVisible()) {
            if (registroEmpleado.isClosed()) {
                desktopPane.add(registroEmpleado);
            }
            registroEmpleado.show();
        }
    }//GEN-LAST:event_registrarEmpleadoItemActionPerformed

    private void btnHacerVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerVentaActionPerformed

        if (this.getVenta() == null) {
            this.setVenta(new MenuVenta(this.getCaja(), this.desktopPane));
            this.desktopPane.add(this.getVenta());
        }
        if (!this.getVenta().isVisible()) {
            if (this.getVenta().isClosed()) {
                this.desktopPane.add(this.getVenta());
            }
            this.getVenta().setVisible(true);
        }
    }//GEN-LAST:event_btnHacerVentaActionPerformed

    private void btnDevoluciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevoluciónActionPerformed

    }//GEN-LAST:event_btnDevoluciónActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        if (this.getInventarioSistema() == null) {
            this.setInventarioSistema(new InventarioSistema(this.getCaja()));
            this.desktopPane.add(this.getInventarioSistema());
        }
        if (!this.getInventarioSistema().isVisible()) {
            if (this.getInventarioSistema().isClosed()) {
                this.desktopPane.add(this.getInventarioSistema());
            }
            this.getInventarioSistema().setVisible(true);
        }
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        if (this.getSistemaReportes()== null) {
            this.setSistemaReportes(new SistemaReportes(this.getCaja(), this, this.desktopPane));
            this.desktopPane.add(this.getSistemaReportes());
        }
        if (!this.getSistemaReportes().isVisible()) {
            if (this.getSistemaReportes().isClosed()) {
                this.desktopPane.add(this.getSistemaReportes());
            }
            this.getSistemaReportes().setVisible(true);
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void initFrames() {
        if (registroEmpleado == null) {
            registroEmpleado = new RegistroEmpleado(this.getCaja());
        }
        desktopPane.add(registroEmpleado);

        if (entrarSistema == null) {
            entrarSistema = new EntrarSistema(this.getCaja(), this);
        }
        desktopPane.add(entrarSistema);
    }

    private void initObjects() {
        caja = new Caja();
        inventario = new Inventario();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDevolución;
    private javax.swing.JButton btnEnter;
    private javax.swing.JToggleButton btnHacerVenta;
    private javax.swing.JToggleButton btnInventario;
    private javax.swing.JButton btnRegisterEmployee;
    private javax.swing.JButton btnReportes;
    private javax.swing.JMenuItem cerrarSesionItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem iniciarSesionItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuIncio;
    private javax.swing.JMenuItem registrarEmpleadoItem;
    private javax.swing.JLabel txtButtonTienda1;
    // End of variables declaration//GEN-END:variables

}
