/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.DetalleVenta;
import BusinessLogic.Venta;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Recibo extends javax.swing.JInternalFrame {

    private MenuVenta menuVenta;
    private DefaultTableModel modeloTabla;
    private Venta venta;
    private double total;

    /**
     * Creates new form Recibo
     */
    public Recibo() {
        initComponents();
        initJTable();
    }

    public Recibo(MenuVenta menuVenta, Venta venta) {
        initComponents();
        initJTable();
        initAdditional(menuVenta,venta);
    }

    public MenuVenta getMenuVenta() {
        return menuVenta;
    }

    public void setMenuVenta(MenuVenta menuVenta) {
        this.menuVenta = menuVenta;
    }

    public Venta getVenta() {
        return venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    //Metodos para la UI
    public void agregarProductoFactura(String descripcion, double precioUnitario, int cantidad,
            double subtotalBruto, double iva, double descuento, double subtotalNeto) {

        Object[] rowData = {
            descripcion,
            precioUnitario,
            cantidad,
            String.format("%.2f", subtotalBruto),
            String.format("%.2f", iva),
            String.format("%.2f", descuento),
            String.format("%.2f", subtotalNeto)
        };

        modeloTabla.addRow(rowData);
    }

    public void mostrarVentasEnRecibo() {
        for (DetalleVenta detalle : venta.getDetalles()) {
            String descripcion = detalle.getProducto().getNombre();
            int cantidad = detalle.getCantidad();
            double precioUni = detalle.getProducto().getPrecio();
            double subtotalBruto = detalle.getSubtotalBruto();
            double iva = detalle.getIva();
            double descuento = detalle.getDescuento();
            double subtotalNeto = detalle.getSubtotalNeto();
            agregarProductoFactura(descripcion, precioUni, cantidad, subtotalBruto,
                    iva, descuento, subtotalNeto);
        }
        
        if (venta.getTotalDescuento() > 0) {
            lblAhorro.setText("¡¡FELICITACIONES!!, en total ahorró: " + venta.getTotalDescuento()
                                + "$. Esperamos que siga confianzo en nosotros para futuras compras.");
        }

    }

    private void mostrarFecha() {
        LocalDateTime fecha = this.getMenuVenta().capturarFecha();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy - HH:mm");
        txtFechaHoy.setText(String.valueOf(fecha.format(formatter)));
    }

    private void mostrarEmpleado() {
        txtEmpleado.setText(this.getMenuVenta().getEmpleadoService().getCajero().getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFactura = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        btnCerrarFactura = new javax.swing.JButton();
        lblEmpleado = new javax.swing.JLabel();
        lblLaSebastiana = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JLabel();
        txtFechaHoy = new javax.swing.JLabel();
        lblAhorro = new javax.swing.JLabel();

        lblFactura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFactura.setText("FACTURA");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Precio Unitario", "Cantidad", "Subtotal Bruto", "IVA", "Descuento", "Subtotal Neto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFactura);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("TOTAL :");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        lblFecha.setText("Fecha : ");

        btnCerrarFactura.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrarFactura.setText("Cerrar");
        btnCerrarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarFacturaActionPerformed(evt);
            }
        });

        lblEmpleado.setText("Empleado : ");

        lblLaSebastiana.setBackground(new java.awt.Color(255, 255, 255));
        lblLaSebastiana.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        lblLaSebastiana.setForeground(new java.awt.Color(70, 123, 254));
        lblLaSebastiana.setText("LA SEBASTIANA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(359, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAhorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(562, 562, 562))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblFactura)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLaSebastiana, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnCerrarFactura)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpleado))
                    .addComponent(txtFechaHoy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(lblAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFactura)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblLaSebastiana)))
                    .addGap(62, 62, 62)
                    .addComponent(lblEmpleado)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotal)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCerrarFactura))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnCerrarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarFacturaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarFacturaActionPerformed

    private void initJTable() {
        modeloTabla = new DefaultTableModel();
        tblFactura.setModel(modeloTabla);
        String[] newColumnNames = {"Descripcion", "Precio Unitario", "Cantidad",
            "Subtotal Bruto", "IVA", "Descuento", "Subtotal Neto"};
        modeloTabla.setColumnIdentifiers(newColumnNames);
        modeloTabla = new DefaultTableModel(newColumnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblFactura.setModel(modeloTabla);
    }
    
    private void initAdditional(MenuVenta menuVenta, Venta venta){
        this.menuVenta = menuVenta;
        this.venta = venta;
        mostrarFecha();
        mostrarEmpleado();
        this.total = venta.getTotalVenta();
        String totalstr = String.format("%.2f", total);
        txtTotal.setText(totalstr);
        txtTotal.setEditable(false);
        mostrarVentasEnRecibo();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAhorro;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLaSebastiana;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblFactura;
    private javax.swing.JLabel txtEmpleado;
    private javax.swing.JLabel txtFechaHoy;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
