/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.Producto;
import BusinessLogic.ProductoService;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ReporteStock extends javax.swing.JInternalFrame {

    private ProductoService productoService;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form ReporteStock
     */
    public ReporteStock() {
        initComponents();
    }

    public ReporteStock(ProductoService productoService) throws Exception {
        initComponents();
        initServices(productoService);
        initJTable();
        this.mostrarVentasEnTabla();
    }

    public ProductoService getProductoService() {
        return productoService;
    }

    public void setProductoService(ProductoService productoService) {
        this.productoService = productoService;
    }

    
    //Metodos de la clase
    
    public void mostrarVentasEnTabla() throws Exception {
        Map<Producto, Integer> productos = this.productoService.filtrarProductosPorStock();

        modeloTabla.setRowCount(0);

        for (Producto producto : productos.keySet()) {
            String nombre = producto.getNombre();
            long id = producto.getId();
            int cantidad = productos.get(producto);
            String alerta = "";
            if (cantidad <= 10) {
                alerta = "⚠️ Stock Critico";
            } else if (cantidad > 50) {
                alerta = "Sobrestock";
            } else {
                alerta = "Normal";
            }

            agregarProducto(id, nombre, cantidad, alerta);
        }
    }

    public void agregarProducto(Long id, String producto, int cantidad,
            String alerta) {

        Object[] rowData = {
            id,
            producto,
            cantidad,
            alerta,
        };

        modeloTabla.addRow(rowData);
    }
    
    private void initServices(ProductoService productoService){
        this.productoService = productoService;
    }
    
    private void initJTable() {
        modeloTabla = new DefaultTableModel();
        tblReporteStock.setModel(modeloTabla);
        String[] newColumnNames = {"ID", "Producto", "Cantidad", "Alerta"};
        modeloTabla.setColumnIdentifiers(newColumnNames);
        modeloTabla = new DefaultTableModel(newColumnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblReporteStock.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReporteStock = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporteStock = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();

        setClosable(true);
        setIconifiable(true);

        lblReporteStock.setText("Reporte Stock de Productos:");

        tblReporteStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Cantidad", "Alerta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReporteStock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(lblReporteStock))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblReporteStock)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReporteStock;
    private javax.swing.JTable tblReporteStock;
    // End of variables declaration//GEN-END:variables
}
