/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.Caja;
import javax.swing.JDesktopPane;

/**
 *
 * @author DELL
 */
public class SistemaReportes extends javax.swing.JInternalFrame {

    private Caja caja;
    private Main main;
    private ReporteStock reporteStock;
    private ReporteVentas reporteVentas;
    private JDesktopPane desktopPane;

    /**
     * Creates new form SistemaReportes
     */
    public SistemaReportes() {
        initComponents();
    }

    public SistemaReportes(Caja caja, Main main, JDesktopPane desktopPane) {
        initComponents();
        this.caja = caja;
        this.main = main;
        this.desktopPane = desktopPane;    
    }
    //Getters y Setters

    public Caja getCaja() {
        return caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }

    public Main getMain() {
        return main;
    }

    public void setMain(Main main) {
        this.main = main;
    }

    public ReporteStock getReporteStock() {
        return reporteStock;
    }

    public void setReporteStock(ReporteStock reporteStock) {
        this.reporteStock = reporteStock;
    }

    public ReporteVentas getReporteVentas() {
        return reporteVentas;
    }

    public void setReporteVentas(ReporteVentas reporteVentas) {
        this.reporteVentas = reporteVentas;
    }

    @Override
    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReportesDeseaHacer = new javax.swing.JLabel();
        btnReporteVentas = new javax.swing.JButton();
        btnReporteStack = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lblReportesDeseaHacer.setText("¿Qué reporte desea consultar?");

        btnReporteVentas.setText("Reporte de Ventas");
        btnReporteVentas.setToolTipText("");
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });

        btnReporteStack.setText("Reporte de Stack");
        btnReporteStack.setToolTipText("");
        btnReporteStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteStackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReporteVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReporteStack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblReportesDeseaHacer)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblReportesDeseaHacer)
                .addGap(39, 39, 39)
                .addComponent(btnReporteVentas)
                .addGap(18, 18, 18)
                .addComponent(btnReporteStack)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        if (this.getReporteVentas() == null) {
            this.setReporteVentas(new ReporteVentas(this.getMain(), this.getDesktopPane()));
            this.getParent().add(this.getReporteVentas());
        }
        if (!this.getReporteVentas().isVisible()) {
            if (this.getReporteVentas().isClosed()) {
                this.getParent().add(this.getReporteVentas());
            }
            this.getReporteVentas().setVisible(true);
        }
    }//GEN-LAST:event_btnReporteVentasActionPerformed

    private void btnReporteStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteStackActionPerformed
       if (this.getReporteStock()== null) {
            this.setReporteStock(new ReporteStock(this.getMain()));
            this.getParent().add(this.getReporteStock());
        }
        if (!this.getReporteStock().isVisible()) {
            if (this.getReporteStock().isClosed()) {
                this.getParent().add(this.getReporteStock());
            }
            this.getReporteStock().setVisible(true);
        }
        /*var ReporteStock = new ReporteStock(parent);
       ReporteStock.setVisible(true);
       ReporteStock.mostrarVentasEnTabla*/
    }//GEN-LAST:event_btnReporteStackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteStack;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JLabel lblReportesDeseaHacer;
    // End of variables declaration//GEN-END:variables
}
