/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.ProductoService;
import BusinessLogic.VentaService;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;

/**
 *
 * @author DELL
 */
public class SistemaReportes extends javax.swing.JInternalFrame {
    
    private Main main;
    private VentaService ventaService;
    private ProductoService productoService;
    private ReporteStock reporteStock;
    private SelectFechaReporte selectFechaReporte;
    private JDesktopPane desktopPane;

    /**
     * Creates new form SistemaReportes
     */
    public SistemaReportes() {
        initComponents();
    }

    public SistemaReportes(Main main, VentaService ventaService, ProductoService productoService, JDesktopPane desktopPane) {
        initComponents();
        initServices( ventaService, productoService);
        this.main = main;
        this.desktopPane = desktopPane;    
    }
    //Getters y Setters

    public Main getMain() {
        return main;
    }

    public void setMain(Main main) {
        this.main = main;
    }

    public ReporteStock getReporteStock() {
        return reporteStock;
    }

    public void setReporteStock(ReporteStock reporteStock) {
        this.reporteStock = reporteStock;
    }

    public SelectFechaReporte getSelectFechaReporte() {
        return selectFechaReporte;
    }

    public void setSelectFechaReporte(SelectFechaReporte selectFechaReporte) {
        this.selectFechaReporte = selectFechaReporte;
    }

    @Override
    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public VentaService getVentaService() {
        return ventaService;
    }

    public void setVentaService(VentaService ventaService) {
        this.ventaService = ventaService;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReportesDeseaHacer = new javax.swing.JLabel();
        btnReporteVentas = new javax.swing.JButton();
        btnReporteStock = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        lblReportesDeseaHacer.setText("¿Qué reporte desea consultar?");

        btnReporteVentas.setBackground(new java.awt.Color(0, 153, 204));
        btnReporteVentas.setText("Reporte de Ventas");
        btnReporteVentas.setToolTipText("");
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });

        btnReporteStock.setBackground(new java.awt.Color(0, 51, 102));
        btnReporteStock.setText("Reporte de Stock");
        btnReporteStock.setToolTipText("");
        btnReporteStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReporteVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReporteStock, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblReportesDeseaHacer)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblReportesDeseaHacer)
                .addGap(39, 39, 39)
                .addComponent(btnReporteVentas)
                .addGap(18, 18, 18)
                .addComponent(btnReporteStock)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        if (this.getSelectFechaReporte() == null) {
            this.setSelectFechaReporte(new SelectFechaReporte(this.main, this.ventaService, this.getDesktopPane()));
            this.getParent().add(this.getSelectFechaReporte());
        }
        if (!this.getSelectFechaReporte().isVisible()) {
            if (this.getSelectFechaReporte().isClosed()) {
                this.getParent().add(this.getSelectFechaReporte());
            }
            this.getSelectFechaReporte().setVisible(true);
        }
    }//GEN-LAST:event_btnReporteVentasActionPerformed

    private void btnReporteStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteStockActionPerformed
       if (this.getReporteStock()== null) {
           try {
               this.setReporteStock(new ReporteStock(this.productoService));
           } catch (Exception ex) {
               Logger.getLogger(SistemaReportes.class.getName()).log(Level.SEVERE, null, ex);
           }
            this.getParent().add(this.getReporteStock());
        }
        if (!this.getReporteStock().isVisible()) {
            if (this.getReporteStock().isClosed()) {
                this.getParent().add(this.getReporteStock());
            }
            this.getReporteStock().getModeloTabla().setRowCount(0);
           try {
               this.getReporteStock().mostrarVentasEnTabla();
           } catch (Exception ex) {
               Logger.getLogger(SistemaReportes.class.getName()).log(Level.SEVERE, null, ex);
           }
            this.getReporteStock().setVisible(true);
        }
        /*var ReporteStock = new ReporteStock(parent);
       ReporteStock.setVisible(true);
       ReporteStock.mostrarVentasEnTabla*/
    }//GEN-LAST:event_btnReporteStockActionPerformed
    
    private void initServices(VentaService ventaService, ProductoService productoService){
        this.ventaService = ventaService;
        this.productoService = productoService;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteStock;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JLabel lblReportesDeseaHacer;
    // End of variables declaration//GEN-END:variables
}
