/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI2;

import BusinessLogic.Venta;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class VentasPeriodo extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private ArrayList<Venta> ventasAMostrar;

    /**
     * Creates new form VentasPeriodo
     */
    public VentasPeriodo() {
        initComponents();
    }

    public VentasPeriodo(ArrayList<Venta> ventasAMotrar) {
        initComponents();
        this.modeloTabla = (DefaultTableModel) tblVentasFiltradas.getModel();
        this.ventasAMostrar = ventasAMotrar;
        mostrarVentasEnTabla(ventasAMotrar);
    }

    public void agregarFilaVenta(Object fecha, Object productos, Double totalVentas) {
        Object[] nuevaFila = {fecha, productos, totalVentas};
        modeloTabla.addRow(nuevaFila);
    }

    public void mostrarVentasEnTabla(ArrayList<Venta> ventasAMostrar) {
        modeloTabla.setRowCount(0);

        for (Venta venta : ventasAMostrar) {
            LocalDateTime fechaVenta = venta.getFecha();
            double totalVenta = venta.getTotalVenta();

            String productosVendidos = venta.getDetalles().stream()
                    .map(detalle -> detalle.getProducto().getNombre()
                    + " x" + detalle.getCantidad())
                    .collect(Collectors.joining(", "));

            agregarFilaVenta(fechaVenta, productosVendidos, totalVenta);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelVentasFiltradas = new javax.swing.JScrollPane();
        tblVentasFiltradas = new javax.swing.JTable();
        scrollVentasFiltradas = new javax.swing.JScrollBar();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        scrollPanelVentasFiltradas1 = new javax.swing.JScrollPane();
        tblVentasFiltradas1 = new javax.swing.JTable();
        scrollVentasFiltradas1 = new javax.swing.JScrollBar();

        scrollPanelVentasFiltradas.setViewportView(tblVentasFiltradas);

        tblVentasFiltradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Productos", "Total Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPanelVentasFiltradas.setViewportView(tblVentasFiltradas);

        tblVentasFiltradas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Productos", "Total Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPanelVentasFiltradas1.setViewportView(tblVentasFiltradas1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVentasFiltradas1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollVentasFiltradas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(scrollVentasFiltradas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVentasFiltradas1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVentasFiltradas, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollVentasFiltradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 358, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 359, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollVentasFiltradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 434, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelVentasFiltradas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 241, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 241, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane scrollPanelVentasFiltradas;
    private javax.swing.JScrollPane scrollPanelVentasFiltradas1;
    private javax.swing.JScrollBar scrollVentasFiltradas;
    private javax.swing.JScrollBar scrollVentasFiltradas1;
    private javax.swing.JTable tblVentasFiltradas;
    private javax.swing.JTable tblVentasFiltradas1;
    // End of variables declaration//GEN-END:variables
}
